library(Seurat)
# devtools::install_github('satijalab/seurat-data')
library(SeuratData)
InstallData("stxBrain")
brain <- LoadData("stxBrain", type = "anterior1")
# BiocManager::install("qs2")
library(qs2)
qs_save(brain, file="visium/visium.qs")
test <- qs_read("visium/visium.qs")
